/*
=====================================================================
 SQL Maintenance Scripts for Civic Request Portal
=====================================================================
 File: 5_Maintenance.sql
 Description: This script contains commands for routine database
              maintenance tasks, including creating a full database
              backup and checking the integrity of the database.
=====================================================================
*/

USE master;
GO
-- =================================================================
-- 1. Full Database Backup
-- Description: Creates a full backup of the database to a .bak file.
--              This is critical for disaster recovery.
-- How to generate: This script was generated by SSMS (Tasks > Back Up > Script).
-- =================================================================



BACKUP DATABASE [NewCivicRequestDB] TO  DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\Backup\NewCivicRequestDB.bak' 
WITH NOFORMAT, NOINIT,  NAME = N'NewCivicRequestDB-Tam Veri tabanı Yedekleme', SKIP, NOREWIND, NOUNLOAD,  STATS = 10
GO

PRINT 'Full database backup completed.';
GO

-- =================================================================
-- 2. Database Integrity Check
-- Description: Checks the allocation and structural integrity of all
--              objects in the database. Running this command regularly
--              helps to detect early signs of data corruption.
-- =================================================================
PRINT 'Starting database integrity check...';

DBCC CHECKDB (N'NewCivicRequestDB')
WITH NO_INFOMSGS;
GO

PRINT 'Database integrity check completed.';
GO

-- =============================================
-- Script Execution Finished
-- =============================================
PRINT 'Maintenance script executed successfully!';
GO